// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6QoO0LGljBTIS0o8_ooYQLFwYglqoBV0',
    appId: '1:1049261215316:web:6464393e3d95118ce827c1',
    messagingSenderId: '1049261215316',
    projectId: 'tako-food',
    authDomain: 'tako-food.firebaseapp.com',
    storageBucket: 'tako-food.appspot.com',
    measurementId: 'G-81VV4VTEHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_-L3G2_6HpPiWDB6JB5j4iUybizEw_iE',
    appId: '1:1049261215316:android:77fd70f24ec0b4b4e827c1',
    messagingSenderId: '1049261215316',
    projectId: 'tako-food',
    storageBucket: 'tako-food.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmC7KFwVLRcF5u0f3cUlmSPSKqsqAtAv0',
    appId: '1:1049261215316:ios:55472554fa6b7830e827c1',
    messagingSenderId: '1049261215316',
    projectId: 'tako-food',
    storageBucket: 'tako-food.appspot.com',
    iosBundleId: 'com.example.takoFood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmC7KFwVLRcF5u0f3cUlmSPSKqsqAtAv0',
    appId: '1:1049261215316:ios:55472554fa6b7830e827c1',
    messagingSenderId: '1049261215316',
    projectId: 'tako-food',
    storageBucket: 'tako-food.appspot.com',
    iosBundleId: 'com.example.takoFood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6QoO0LGljBTIS0o8_ooYQLFwYglqoBV0',
    appId: '1:1049261215316:web:fb029ec2b63a42afe827c1',
    messagingSenderId: '1049261215316',
    projectId: 'tako-food',
    authDomain: 'tako-food.firebaseapp.com',
    storageBucket: 'tako-food.appspot.com',
    measurementId: 'G-8J251PXGQ0',
  );
}
